# Generated by Django 2.1.4 on 2018-12-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_remove_edificio_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='Nivel',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nivel'),
        ),
    ]
