# Generated by Django 2.1.4 on 2019-01-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_edificio_nivel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edificio',
        ),
    ]
