# Generated by Django 2.1.4 on 2019-01-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details', '0006_delete_edificio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(blank=True, max_length=80, verbose_name='Nivel')),
                ('Metros', models.CharField(blank=True, max_length=80, verbose_name='Metros')),
            ],
        ),
    ]
