# Generated by Django 2.1.4 on 2019-01-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_edificio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metros', models.DecimalField(blank=True, decimal_places=2, max_digits=6, max_length=80, verbose_name='Metros')),
                ('Sanitarios', models.IntegerField(blank=True, verbose_name='Número de Baños')),
                ('Plano', models.FileField(upload_to=None)),
            ],
        ),
        migrations.AddField(
            model_name='edificio',
            name='Nombre',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='Metros',
            field=models.FloatField(blank=True, max_length=80, verbose_name='Metros'),
        ),
    ]
