# Generated by Django 2.1.4 on 2019-01-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_auto_20190103_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='Nivel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='details.Edificio'),
        ),
    ]
