# Generated by Django 2.1.4 on 2019-01-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_nivel_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='Plano',
        ),
    ]
