# Generated by Django 2.1.4 on 2019-01-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_impuestos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsoCajon', models.CharField(choices=[('PC', 'PC'), ('PS', 'PS'), ('HR', 'HR')], default='PC', max_length=80)),
            ],
        ),
    ]
