# Generated by Django 2.1.5 on 2019-02-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0012_estacionamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='UsoCajon',
            field=models.CharField(choices=[('PC', 'Contrato'), ('PS', 'Pensión'), ('HR', 'Renta por Hora')], default='PC', max_length=80, verbose_name='Uso de cajón'),
        ),
    ]
