# Generated by Django 2.1.4 on 2019-02-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_auto_20190201_1042'),
        ('details', '0013_auto_20190202_1704'),
    ]

    operations = [
    ]
