# Generated by Django 2.1.4 on 2019-02-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0015_cliente_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='Nivel',
            field=models.CharField(max_length=80, verbose_name='Nivel'),
        ),
    ]
