# Generated by Django 2.1.4 on 2019-02-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0016_auto_20190225_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Nivel',
        ),
        migrations.AlterField(
            model_name='edificio',
            name='Nivel',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nivel'),
        ),
    ]
