# Generated by Django 2.1.4 on 2019-02-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0017_auto_20190225_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='IdCliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='details.Cliente'),
        ),
    ]
