# Generated by Django 2.1.4 on 2019-02-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0019_auto_20190225_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='Folio',
            field=models.CharField(default=None, max_length=80, verbose_name='Folio de contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='Metros_contratados',
            field=models.PositiveIntegerField(blank=True, verbose_name='Metros arrendados'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='Metros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, max_length=80, verbose_name='Metros'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='Nivel',
            field=models.PositiveIntegerField(blank=True, max_length=80, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='Cajon',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='Cajón Número'),
        ),
        migrations.AlterField(
            model_name='impuestos',
            name='Porcentaje',
            field=models.PositiveIntegerField(blank=True, verbose_name='Cuota (%)'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='Sanitarios',
            field=models.PositiveIntegerField(blank=True, verbose_name='Número de Baños'),
        ),
    ]
