# Generated by Django 2.1.4 on 2019-02-25 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0021_auto_20190225_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='Metros',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Maximum Discount'),
        ),
    ]
