# Generated by Django 2.1.4 on 2019-02-25 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0022_auto_20190225_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='Metros',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Metros'),
        ),
    ]
