# Generated by Django 2.1.4 on 2019-02-26 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0023_auto_20190225_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='Precio_metro',
        ),
        migrations.AddField(
            model_name='contrato',
            name='Precio_Metro',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio por metro cuadrado'),
        ),
        migrations.AlterField(
            model_name='impuestos',
            name='Nombre',
            field=models.CharField(default='%', max_length=80, verbose_name='Nombre del impuesto'),
        ),
        migrations.AlterField(
            model_name='impuestos',
            name='Porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='Metros',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Metros'),
        ),
    ]
