# Generated by Django 2.1.5 on 2019-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0024_auto_20190226_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Valor')),
            ],
        ),
        migrations.RemoveField(
            model_name='impuestos',
            name='Porcentaje',
        ),
        migrations.AddField(
            model_name='impuestos',
            name='Porcentaje',
            field=models.ManyToManyField(to='details.Impuesto'),
        ),
    ]
