# Generated by Django 2.1.5 on 2019-02-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0025_auto_20190227_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuesto',
            name='Porcentaje',
        ),
        migrations.AddField(
            model_name='impuesto',
            name='Nombre',
            field=models.CharField(default='%', max_length=80, verbose_name='Nombre del impuesto'),
        ),
        migrations.AddField(
            model_name='impuestos',
            name='PorcentajeNtoM',
            field=models.ManyToManyField(to='details.Impuesto'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='Impuesto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='details.Impuesto'),
        ),
        migrations.RemoveField(
            model_name='impuestos',
            name='Porcentaje',
        ),
        migrations.AddField(
            model_name='impuestos',
            name='Porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, verbose_name='Valor'),
        ),
    ]
