# Generated by Django 2.1.5 on 2019-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0027_auto_20190227_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestos',
            name='Porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor'),
        ),
    ]
