# Generated by Django 2.1.5 on 2019-02-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0029_auto_20190227_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='Porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor'),
        ),
    ]
