# Generated by Django 2.1.5 on 2019-02-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0030_auto_20190227_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuestos',
            name='Porcentaje',
        ),
    ]
