# Generated by Django 2.1.5 on 2019-02-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0031_remove_impuestos_porcentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuesto',
            name='Porcentaje',
        ),
        migrations.AddField(
            model_name='impuesto',
            name='Nombre',
            field=models.CharField(default='%', max_length=80, verbose_name='Nombre del impuesto'),
        ),
        migrations.AddField(
            model_name='impuestos',
            name='Porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor'),
        ),
    ]
