# Generated by Django 2.1.5 on 2019-02-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0032_auto_20190227_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuesto',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='impuestos',
            name='Porcentaje',
        ),
        migrations.AddField(
            model_name='impuesto',
            name='Porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor'),
        ),
    ]
