# Generated by Django 2.1.5 on 2019-02-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0033_auto_20190227_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuestos',
            name='PorcentajeNtoM',
        ),
        migrations.AddField(
            model_name='impuestos',
            name='Porcentaje_NtoM',
            field=models.ManyToManyField(to='details.Impuesto'),
        ),
    ]
