# Generated by Django 2.1.5 on 2019-02-27 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0035_auto_20190227_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='Impuesto',
        ),
        migrations.AddField(
            model_name='contrato',
            name='Nombre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='details.Impuestos'),
        ),
    ]
