# Generated by Django 2.1.5 on 2019-02-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0036_auto_20190227_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='impuestos',
            name='Porcentaje_NtoM',
        ),
        migrations.AddField(
            model_name='contrato',
            name='Porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='impuestos',
            name='Porcentaje',
            field=models.ManyToManyField(to='details.Contrato'),
        ),
        migrations.DeleteModel(
            name='Impuesto',
        ),
    ]
