# Generated by Django 2.1.5 on 2019-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0037_auto_20190227_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='Porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor'),
        ),
    ]
