# Generated by Django 2.1.5 on 2019-02-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0038_auto_20190227_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='Porcentaje',
        ),
        migrations.AddField(
            model_name='contrato',
            name='Nombre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='details.Impuestos'),
        ),
        migrations.RemoveField(
            model_name='impuestos',
            name='Porcentaje',
        ),
        migrations.AddField(
            model_name='impuestos',
            name='Porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Valor'),
        ),
    ]
