# Generated by Django 2.1.5 on 2019-02-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0039_auto_20190227_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='Nombre',
        ),
        migrations.AddField(
            model_name='contrato',
            name='Nombre',
            field=models.ManyToManyField(blank=True, max_length=80, to='details.Impuestos'),
        ),
    ]
