# Generated by Django 2.1.5 on 2019-02-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0040_auto_20190227_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='Cajones',
        ),
        migrations.AddField(
            model_name='contrato',
            name='Cajon',
            field=models.ManyToManyField(blank=True, max_length=80, to='details.Estacionamiento'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='Cajon',
            field=models.CharField(blank=True, default=None, max_length=1, verbose_name='Cajón Número'),
        ),
    ]
