# Generated by Django 2.1.5 on 2019-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0042_contrato_fecha_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='Fecha_f',
            field=models.DateField(blank=True, default=None, verbose_name='Fin de contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='Fecha_i',
            field=models.DateField(default=None, verbose_name='Inicio de contrato'),
        ),
    ]
